version: "3.8"

services:
  mysql:
      image: mysql:latest
      container_name: cursosql
      command: 
        --default-authentication-plugin=mysql_native_password
      restart: always
      ports:
        - '3306:3306'
      #volumes:
        # - /var/lib/mysql:ro
        # - $PWD/data:/var/lib/mysql
        # - "./create-db-template.sql:/docker-entrypoint-initdb.d/1.sql"
      environment:
        MYSQL_DATABASE: cursosql
        MYSQL_ROOT_PASSWORD: senha
        MYSQL_USER: curso
        MYSQL_PASSWORD: curso
        MYSQL_ROOT_HOST: '%'
        TZ: America/Sao_Paulo
      # networks:
      # - mysql-curso-network

  phpmyadmin:
      image: phpmyadmin
      restart: always
      ports:
      - 8088:80
      environment:
        - PMA_ARBITRARY=1
      depends_on:
        - mysql
      # networks:
      # - mysql-curso-network

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8089:8080
  #   depends_on:
  #       - mysql
  #   networks:
  #     - mysql-curso-network

# networks: 
#   mysql-curso-network: 
#     driver: bridge